# Project Name
TARGET := drone

# Sources
CPP_SOURCES := math/models.cpp screen/Display.cpp screen/DisplayTester.cpp

# Library Locations
LIBDAISY_DIR := ../../libDaisy/
DAISYSP_DIR := ../../DaisySP/

CPP_STANDARD := -std=gnu++17

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
